spring:
  config:
    activate:
      on-profile: dev
name: skbCourse-dev
my:
  studentName: dev
  color: red
  courseThemes:
  - Sample theme 1
  - Sample theme 2
  - Sample theme 3
  home: ${JAVA_HOME:default}
---
spring:
  config:
    activate:
      on-profile: test
name: skbCourse-test
my:
  studentName: test
  color: blue
  courseThemes:
  - Test theme 1
  - Test theme 2
  - Test theme 3
  home: ${JAVA_HOME:default}
---
spring:
  config:
    activate:
      on-profile: prod
name: skbCourse-prod
my:
  studentName: prod
  courseThemes:
    - git
    - Spring boot hello
    - DI
  home: ${JAVA_HOME:default}